version: '3.8'
services:
  web:
    build: .
    env_file:
      - env_file.env
    image: warnex/storeapi:${STOREAPI_VERSION}
    ports:
      - "${WEB_PORT}:80"


  web2:
    build: .
    image: warnex/storeapi:latest
    env_file:
      - env_file.env
    ports:
      - "${WEB_PORT2}:80"
  redis:
    env_file:
      - env_file.env
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf
      - redis-data:/data
  nginx:
    env_file:
      - env_file.env
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf:ro
  
volumes:
  redis-data:
